-- Create or replace the PIPE for the ALBUMS table
CREATE OR REPLACE PIPE MANAGE_DB.PIPES.ALBUM_PIPE 
AUTO_INGEST = TRUE 
AS 
COPY INTO SPOTIFY_DB.SPOTIFY_TOP_100.ALBUMS
FROM @MANAGE_DB.EXTERNAL_STAGES.SPOTIFY_S3_BUCKET
PATTERN = 'album_data/.*';


-- Create or replace the PIPE for the ARTISTS table
CREATE OR REPLACE PIPE MANAGE_DB.PIPES.ARTIST_PIPE 
AUTO_INGEST = TRUE 
AS 
COPY INTO SPOTIFY_DB.SPOTIFY_TOP_100.ARTISTS
FROM @MANAGE_DB.EXTERNAL_STAGES.SPOTIFY_S3_BUCKET
PATTERN = 'artist_data/.*';


-- Create or replace the PIPE for the SONGS table
CREATE OR REPLACE PIPE MANAGE_DB.PIPES.SONG_PIPE 
AUTO_INGEST = TRUE 
AS 
COPY INTO SPOTIFY_DB.SPOTIFY_TOP_100.SONGS
FROM @MANAGE_DB.EXTERNAL_STAGES.SPOTIFY_S3_BUCKET
PATTERN = 'song_data/.*';


-- Verify PIPE creation
SHOW PIPES IN DATABASE MANAGE_DB;
